services:
  siwe:
    image: bozemanpass/siwe-express-example:stack
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      ETHEREUM_RPC_URL: ${ETHEREUM_RPC_URL}
      FAUCET_PRIVATE_KEY: ${FAUCET_PRIVATE_KEY}
      LISTEN_ADDR: ${LISTEN_ADDR}
      LISTEN_PORT: ${LISTEN_PORT}
      MINIMUM_ACCOUNT_BALANCE: ${MINIMUM_ACCOUNT_BALANCE}
      REQUIRE_SAME_NETWORK: ${REQUIRE_SAME_NETWORK}
      REQUIRE_WHITELISTED_ACCOUNTS: ${REQUIRE_WHITELISTED_ACCOUNTS}
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      WHITELIST_CONTRACT_ADDRESS: ${WHITELIST_CONTRACT_ADDRESS}
    volumes:
      - siwe-data:/data
    ports:
      - "3200" # @stack http-proxy /

volumes:
  siwe-data:
