requires:
  stacks:
    - ref: bozemanpass/fixturenet-eth-stack
      path: stacks/fixturenet-eth
    - ref: bozemanpass/din-caddy-stack
      path: stacks/din-caddy
    - ref: bozemanpass/siwe-express-example
      path: stack/siwe-express-example