name: siwe-on-fixturenet
requires:
  stacks:
    - ref: bozemanpass/fixturenet-eth-stack
      path: stacks/fixturenet-eth
      http-proxy-prefix: /eth
    - ref: bozemanpass/siwe-express-example
      path: stacks/siwe-express-example
      http-proxy-prefix: /
