name: siwe-express-example
description: "siwe-express-example"
containers:
  - name: bozemanpass/siwe-express-example
pods:
  - name: siwe-express-example
    post_start_command: "./scripts/deploy-contract.sh"
