name: Build Container Image

on:
  push:
    branches:
      - main
      - build-test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate container image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/siwe-express-example
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long
            # if is in MAIN branch, also tag as latest
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Log in to Container Image Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CI_COMMIT_SHA=${{ github.sha }}
